name:                bytecode-interpreter
version:             0.1.0.0
license:             BSD3
author:              "Diego Murillo"
maintainer:          "diego.spd@gmail.com"
copyright:           "2021 Diego Murillo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bytecode-interpreter#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- containers
- hashmap
- transformers
- microlens-platform
- mtl

library:
  source-dirs: src

executables:
  bytecode-interpreter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytecode-interpreter

tests:
  bytecode-interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytecode-interpreter
